# Generated by Django 3.1.7 on 2021-04-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_role',
            new_name='role',
        ),
    ]
