# Generated by Django 3.1.7 on 2021-04-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210405_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MAHASISWA', 'MAHASISWA'), ('ADMIN PKM', 'ADMIN PKM'), ('ADMIN FASTUR', 'ADMIN FASTUR'), ('ADMIN HUMAS', 'ADMIN HUMAS'), ('ADMIN KERJA', 'UNIT KERJA')], max_length=30),
        ),
    ]
