# Generated by Django 3.1.7 on 2021-04-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_detailkegiatan_izinkegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkegiatan',
            name='alasan_penolakan',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
